### ISSUE TITLE
Failed prop type: Invalid prop `setIsProcessing` of type `boolean` supplied to `CurrentRate`, expected `function`

### ISSUE THREAD

**Issue by WiktorKwasniak** [IIS-ZPI/ZPI2022_zaoczni_NoProblem#48]
Frontend build keeps failing on test step. 1/1 tests can't pass. Please investigate failing test and make approriate fix. 
_ERROR: Failed prop type: Invalid prop `setIsProcessing` of type `boolean` supplied to `CurrentRate`, expected `function`_
[Example log](https://github.com/IIS-ZPI/ZPI2022_zaoczni_NoProblem/actions/runs/3980347239/jobs/6823362081)

**Comment by 229258** [comment]
Fix for that was introduced in PR #54. Could you retest @WiktorKwasniak?

**Comment by WiktorKwasniak** [comment]
Checked. Issue fixed
